//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVOGADO_CONTRARIO_COMENTARIO
    {
        public int ACCO_CD_ID { get; set; }
        public int ADCO_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> ACCO_DT_COMENTARIO { get; set; }
        public string ACCO_DS_COMENTARIO { get; set; }
        public Nullable<int> ACCO_IN_ATIVO { get; set; }
    
        public virtual ADVOGADO_CONTRARIO ADVOGADO_CONTRARIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
