//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVOGADO_CONTRARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADVOGADO_CONTRARIO()
        {
            this.ADVOGADO_CONTRARIO_ANEXO = new HashSet<ADVOGADO_CONTRARIO_ANEXO>();
            this.ADVOGADO_CONTRARIO_COMENTARIO = new HashSet<ADVOGADO_CONTRARIO_COMENTARIO>();
            this.PROCESSO = new HashSet<PROCESSO>();
        }
    
        public int ADCO_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string ADCO_NM_NOME { get; set; }
        public string ADCO_NR_OAB { get; set; }
        public string ADCO_NM_EMAIL { get; set; }
        public string ADCO_NR_TELEFONE { get; set; }
        public string ADCO_NR_CELULAR { get; set; }
        public string ADCO_NR_WHATSAPP { get; set; }
        public string ADCO_NM_REDES_SOCIAIS { get; set; }
        public string ADCO_NM_WEBSITE { get; set; }
        public string ADCO_NM_ENDERECO { get; set; }
        public string ADCO_NR_NUMERO { get; set; }
        public string ADCO_NR_COMPLEMENTO { get; set; }
        public string ADCO_NM_BAIRRO { get; set; }
        public string ADCO_NM_CIDADE { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
        public string ADCO_NR_CEP { get; set; }
        public Nullable<int> ADCO_IN_ATIVO { get; set; }
        public string ADCO_TX_OBSERVACOES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADVOGADO_CONTRARIO_ANEXO> ADVOGADO_CONTRARIO_ANEXO { get; set; }
        public virtual ASSINANTE ASSINANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADVOGADO_CONTRARIO_COMENTARIO> ADVOGADO_CONTRARIO_COMENTARIO { get; set; }
        public virtual UF UF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCESSO> PROCESSO { get; set; }
    }
}
