//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.CLIENTE_ANEXO = new HashSet<CLIENTE_ANEXO>();
            this.CLIENTE_COMENTARIO = new HashSet<CLIENTE_COMENTARIO>();
            this.CLIENTE_CONTATO = new HashSet<CLIENTE_CONTATO>();
            this.CLIENTE_DEPENDENTE = new HashSet<CLIENTE_DEPENDENTE>();
            this.CLIENTE_MENSAGEM = new HashSet<CLIENTE_MENSAGEM>();
            this.CLIENTE_QUADRO_SOCIETARIO = new HashSet<CLIENTE_QUADRO_SOCIETARIO>();
            this.DOCUMENTO = new HashSet<DOCUMENTO>();
            this.PROCESSO = new HashSet<PROCESSO>();
        }
    
        public int CLIE_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> CACL_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public Nullable<int> TIPE_CD_ID { get; set; }
        public string CLIE_AQ_FOTO { get; set; }
        public string CLIE_NM_NOME { get; set; }
        public string CLIE_SG_APELIDO { get; set; }
        public string CLIE_NR_CPF { get; set; }
        public string CLIE_NR_RG { get; set; }
        public Nullable<System.DateTime> CLIE_DT_EMISSAO_RG { get; set; }
        public string CLIE_NM_ORGAO_EMISSAO_RG { get; set; }
        public string CLIE_NR_TITULO_ELEITOR { get; set; }
        public string CLIE_NM_RAZAO { get; set; }
        public string CLIE_NR_CNPJ { get; set; }
        public string CLIE_NR_INSCRICAO_ESTADUAL { get; set; }
        public string CLIE_NR_INSCRICAO_MUNICIPAL { get; set; }
        public string CLIE_NM_EMAIL { get; set; }
        public string CLIE_NR_TELEFONE { get; set; }
        public string CLIE_NR_WHATSAPP { get; set; }
        public string CLIE_NR_CELULAR { get; set; }
        public string CLIE_NM_WEBSITE { get; set; }
        public string CLIE_NM_REDES_SOCIAIS { get; set; }
        public string CLIE_NM_ENDERECO { get; set; }
        public string CLIE_NR_NUMERO { get; set; }
        public string CLIE_NM_COMPLEMENTO { get; set; }
        public string CLIE_NM_BAIRRO { get; set; }
        public string CLIE_NM_CIDADE { get; set; }
        public string CLIE_NR_CEP { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
        public string CLIE_NM_ENDERECO_COMERCIAL { get; set; }
        public string CLIE_NR_NUMERO_COMERCIAL { get; set; }
        public string CLIE_NR_COMPLEMENTO_COMERCIAL { get; set; }
        public string CLIE_NM_BAIRRO_COMERCIAL { get; set; }
        public string CLIE_NM_CIDADE_COMERCIAL { get; set; }
        public string CLIE_NR_CEP_COMERCIAL { get; set; }
        public Nullable<int> UF_CD_ID_COMERCIAL { get; set; }
        public Nullable<int> PROF_CD_ID { get; set; }
        public string CLIE_NM_EMPRESA { get; set; }
        public string CLIE_NM_CARGO { get; set; }
        public string CLIE_NR_CARTEIRA_CLASSE { get; set; }
        public Nullable<int> ORCL_CD_ID { get; set; }
        public Nullable<System.DateTime> CLIE_DT_CARTEIRA_CLASSE_EMISSAO { get; set; }
        public Nullable<System.DateTime> CLIE_DT_ADMISSAO { get; set; }
        public Nullable<System.DateTime> CLIE_DT_DESLIGAMENTO { get; set; }
        public string CLIE_NM_MOTIVO_DESLIGAMENTO { get; set; }
        public Nullable<int> TIDE_CD_ID { get; set; }
        public string CLIE_NR_CTPS { get; set; }
        public string CLIE_NR_SERIE_CTPS { get; set; }
        public string CLIE_NR_NIT { get; set; }
        public string CLIE_NM_PAI { get; set; }
        public string CLIE_NM_MAE { get; set; }
        public Nullable<System.DateTime> CLIE_DT_NASCIMENTO { get; set; }
        public Nullable<int> SEXO_CD_ID { get; set; }
        public Nullable<int> ESCI_CD_ID { get; set; }
        public Nullable<int> ESCO_CD_ID { get; set; }
        public string CLIE_NM_NATURALIDADE { get; set; }
        public Nullable<int> UF_CD__NATURALIADE { get; set; }
        public string CLIE_NM_NACIONALIDADE { get; set; }
        public string CLIE_TX_OBSERVACOES { get; set; }
        public System.DateTime CLIE_DT_CADASTRO { get; set; }
        public int CLIE_IN_ATIVO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual CATEGORIA_CLIENTE CATEGORIA_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_ANEXO> CLIENTE_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_COMENTARIO> CLIENTE_COMENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_CONTATO> CLIENTE_CONTATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_DEPENDENTE> CLIENTE_DEPENDENTE { get; set; }
        public virtual ESCOLARIDADE ESCOLARIDADE { get; set; }
        public virtual ESTADO_CIVIL ESTADO_CIVIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_MENSAGEM> CLIENTE_MENSAGEM { get; set; }
        public virtual ORGAO_CLASSE ORGAO_CLASSE { get; set; }
        public virtual PROFISSAO PROFISSAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_QUADRO_SOCIETARIO> CLIENTE_QUADRO_SOCIETARIO { get; set; }
        public virtual SEXO SEXO { get; set; }
        public virtual TIPO_DESLIGAMENTO TIPO_DESLIGAMENTO { get; set; }
        public virtual TIPO_PESSOA TIPO_PESSOA { get; set; }
        public virtual UF UF { get; set; }
        public virtual UF UF1 { get; set; }
        public virtual UF UF2 { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTO> DOCUMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCESSO> PROCESSO { get; set; }
    }
}
