//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_DEPENDENTE
    {
        public int CLDE_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public string CLDE_NM_NOME { get; set; }
        public Nullable<System.DateTime> CLDE_DT_NASCIMENTO { get; set; }
        public Nullable<int> GRPA_CD_ID { get; set; }
        public string CLDE_DS_NOTAS { get; set; }
        public int CLDE_IN_ATIVO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual GRAU_PARENTESCO GRAU_PARENTESCO { get; set; }
    }
}
