//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_MENSAGEM
    {
        public int CLME_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int TIME_CD_ID { get; set; }
        public Nullable<System.DateTime> CLME_DT_ENVIO { get; set; }
        public string CLME_DS_TEXTO { get; set; }
        public Nullable<int> CLME_IN_ENVIADO { get; set; }
        public int CLME_IN_ATIVO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual TIPO_MENSAGEM TIPO_MENSAGEM { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
