//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCUMENTO()
        {
            this.DOCUMENTO_METADADO = new HashSet<DOCUMENTO_METADADO>();
        }
    
        public int DOCU_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public int PROC_CD_ID { get; set; }
        public string DOCU_NM_NOME { get; set; }
        public string DOCU_DS_DESCRICAO { get; set; }
        public Nullable<System.DateTime> DOCU_DT_CADASTRO { get; set; }
        public Nullable<int> CLAS_CD_ID { get; set; }
        public string DOCU_AQ_ARQUIVO { get; set; }
        public Nullable<int> DOCU_IN_VISUALIZACAO { get; set; }
        public Nullable<int> DOCU_IN_DOWNLOAD { get; set; }
        public string DOCU_TX_OBSERVACAO { get; set; }
        public Nullable<int> DOCU_IN_ATIVO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual CLASSE CLASSE { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTO_METADADO> DOCUMENTO_METADADO { get; set; }
        public virtual PROCESSO PROCESSO { get; set; }
    }
}
