//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        public int EMPR_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> TIPE_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public string EMPR_NR_CNPJ { get; set; }
        public string EMPR_NR_CPF { get; set; }
        public string EMPR_NM_NOME { get; set; }
        public string EMPR_NM_RAZAO_SOCIAL { get; set; }
        public string EMPR_NM_ENDERECO { get; set; }
        public string EMPR_NM_BAIRRO { get; set; }
        public string EMPR_NM_CIDADE { get; set; }
        public string EMPR_NR_CEP { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
        public string EMPR_NR_INSCRICAO_MUNICIPAL { get; set; }
        public string EMPR_NR_INSCRICAO_ESTADUAL { get; set; }
        public string EMPR_AQ_LOGO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual TIPO_PESSOA TIPO_PESSOA { get; set; }
        public virtual UF UF { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
