//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORO()
        {
            this.PROCESSO = new HashSet<PROCESSO>();
            this.VARA = new HashSet<VARA>();
        }
    
        public int FORO_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int CICO_CD_ID { get; set; }
        public string FORO_NM_NOME { get; set; }
        public string FORO_DS_DESCRICAO { get; set; }
        public string FORO_NM_ENDERECO { get; set; }
        public string FORO_NR_NUMERO { get; set; }
        public string FORO_NR_COMPLEMENTO { get; set; }
        public string FORO_NM_BAIRRO { get; set; }
        public string FORO_NM_CIDADE { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
        public string FORO_NR_CEP { get; set; }
        public int FORO_IN_ATIVO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual CIDADE_COMARCA CIDADE_COMARCA { get; set; }
        public virtual UF UF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCESSO> PROCESSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VARA> VARA { get; set; }
    }
}
