//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODELO_DOCUMENTO
    {
        public int MODO_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string MODO_NM_NOME { get; set; }
        public string MODO_DS_DESCRICAO { get; set; }
        public string MODO_AQ_ARQUIVO { get; set; }
        public string MODO_TX_TEXTO { get; set; }
        public Nullable<int> MODO_IN_ATIVO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
    }
}
