//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSO_PROFISSIONAL_ALOCADO
    {
        public int PRPA_CD_ID { get; set; }
        public int PROC_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> PRPA_DT_INICIO { get; set; }
        public Nullable<System.DateTime> PRPA_DT_SAIDA { get; set; }
        public string PRPA_NM_ATRIBUICAO { get; set; }
        public Nullable<int> PRPA_IN_ATIVO { get; set; }
    }
}
