//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_JUSTICA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_JUSTICA()
        {
            this.PROCESSO = new HashSet<PROCESSO>();
            this.REGIAO_JUSTICA = new HashSet<REGIAO_JUSTICA>();
        }
    
        public int TIJU_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string TIJU_NM_NOME { get; set; }
        public string TIJU_DS_DESCRICAO { get; set; }
        public int TIJU_IN_ATIVO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCESSO> PROCESSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGIAO_JUSTICA> REGIAO_JUSTICA { get; set; }
    }
}
