//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VARA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VARA()
        {
            this.PROCESSO = new HashSet<PROCESSO>();
        }
    
        public int VARA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int FORO_CD_ID { get; set; }
        public string VARA_NM_NOME { get; set; }
        public string VARA_DS_DESCRICAO { get; set; }
        public string VARA_NM_JUIZ { get; set; }
        public string VARA_NM_ENDERECO { get; set; }
        public string VARA_NR_NUMERO { get; set; }
        public string VARA_NR_COMPLEMENTO { get; set; }
        public string VARA_NM_BAIRRO { get; set; }
        public string VARA_NM_CIDADE { get; set; }
        public string VARA_NR_CEP { get; set; }
        public string VARA_TX_OBSERVACOES { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
        public int VARA_IN_ATIVO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual FORO FORO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCESSO> PROCESSO { get; set; }
        public virtual UF UF { get; set; }
    }
}
